---
jupyter:
  jupytext:
    formats: ipynb,Rmd
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

<!-- #region -->
# Introduction

Plotting is one of the most important tasks that engineers and scientists use computers for. 
Plots are used to:

- present and understand data; and
- to check computed results visually.

The most widely used Python module for plotting is Matplotlib (<http://matplotlib.org/>), and this is what we will use. Matplotlib is extremely powerful and we will use only a small fraction of its functionality.
The material in this notebook will provide you with a basis that you can build 
upon for more advanced plotting by searching online resources. A good place to start for 
a wide range of examples is the Matplotlib Gallery (http://matplotlib.org/gallery.html).

We will use the tools presented in this notebook to visualise results in subsequent notebooks.

> This is a longer activity - this a reflection of the importance of plotting. The next activity
> is shorter in compensation.

> Some exercises in this notebook are challenging. Use the Moodle forum to get help.



## Why do we plot programmatically?

Producing plots via a program is very powerful. It allows you to explore and manipulate 
data in sophisticated ways. It also allows you to make plotting interactive; 
from a large and complex data
set you can design interfaces for you and others to query the data and have it displayed graphically, 
possibly over the Internet.
It also allows you to automated the fetching and processing of  data from online sources or 
from laboratory equipment.


## Objectives

- Introduction to a programmatic approach to plotting 
- Create line plots and bar charts from discrete data sets
- Create line plots of mathematical functions
- Create histograms for distribution-like data 
- Develop interactive plots
- Create contour plots of functions of two variables

> This notebook uses interactive widgets - you will need to execute the notebook to see the widgets.
<!-- #endregion -->

## Installing modules

In this notebook we will use the module `quandl` to fetch financial data from the Internet for plotting. 
Quandl is not  available by default in Python environments, so we need to install it. 
The usual way to install a module is:
```
!pip install module-name
```
If you are using the Anaconda Python environment, an alternative is: 
```
!conda install -yc conda-forge module-name
```

Below we install the `quandl` package. You can skip over the details, and it should just work. The code is a little complex because it is designed work for a range of different Python environments. If you get an error message in the following code blocks, send a message with the error to the Moodle forum.

To install the `quandl` package:

```{python}
# %autosave 0
```

```{python}
import sys
if 'conda' in sys.version:  # Install using conda if we're using Anaconda Python
    !conda install -yc conda-forge quandl
else:  # Install using pip on others systems
    try:
        !{sys.executable} -m pip -q install quandl  # Try to install globally
        import quandl
    except ImportError:
        !{sys.executable} -m pip -q install --user quandl  # Install in user space
```

We will be using the `ipywidgets` module for interactive plots. It has already been configured for you on
https://notebooks.azure.com/, so the below is necessary only if using other environments.

```{python}
try:
    import ipywidgets
except ImportError:
    try:
        !{sys.executable} -m pip -q install ipywidgets
        import ipywidgets
    except ImportError:
        !{sys.executable} -m pip -q --user install ipywidgets
    finally:
        !jupyter nbextension enable --py widgetsnbextension
        print("You will need to refresh your browser page")
```

# Matplotlib

To use Matplotlib, we need to import it. We will be using the `pyplot` interface to Matplotlib, so we need to import `pyplot` too:

```{python}
import matplotlib
import matplotlib.pyplot as plt
```

We will be using NumPy when producing plots, so we import it now:

```{python}
import numpy as np
```

Matplotlib is a regular Python library that can be used outside of Jupyter notebooks to display plots to the screen or to write plots to a file. To have plots appear inline in a Jupyter notebook, we need the 'magic' command
[`%matplotlib inline`](Notebook%20tips.ipynb#Matplotlib):

```{python}
# %matplotlib inline

```

If you want the increase the default font size, use:
```python
matplotlib.rcParams.update({'font.size': 16})
```


# Simple line plots

Given the data set

$x$ value  | $f$ value
----------:|----------:
-1         | -1
3          | -2
4          | 7
8          | 13
10         | 1

we want to create a line plot of $x$-values (horizontal axis) against the $f$ values (vertical axis).

We first create a list of `x` values and a list of `f` values:

```{python}
x = [-1, 3, 4, 8 , 10]
f = [-1, -2, 7, 13 , 1]
```

We now use the `plt.plot` function to produce a line plot:

```{python}
plt.plot(x, f);
```

Note that `x` and `f` are lists, but they could be any ordered array-like structure, e.g. tuple or NumPy array. 

We can improve the plot by adding axis labels, a title and dots to indicate data points.

```{python}
# Plot data with a line and dots at the data points (this is what '-o' does)
plt.plot(x, f, '-o')  

# Attach labels and title (using LaTeX syntax)
plt.xlabel('$x$')
plt.ylabel('$f$')
plt.title("Simple plot of $x$ vs $f$");
```

To change the colour of the line to red and use crosses at the data points, and to save the
plot to the file `my-plot.png`, we can do the following:

```{python}
# Plot data with a red solid line and crosses at the data points (this is what '-xr' does)
plt.plot(x, f, '-xr')

# Attach labels and title
plt.xlabel('$x$')
plt.ylabel('$f$')
plt.title("Simple plot of $f$ against $x$")

# Save plot to file
plt.savefig("my-plot.png");
```

Upon executing the notebook, the file `my-plot.png` should appear in the same directory as the notebook.
You could use the file to include the plot in a document or presentation.


# Plotting mathematical functions of one variable

Line plots of a mathematical function are created by evaluating the function at a large number of points. If we use enough points, the graph of a function will appear smooth.

To plot the function:

$$
f(x) = \sin(x)
$$

the first step is to create an array of values at which we want to evaluate the function. We can use the NumPy function `linspace` to do this: 

```{python}
num_points = 100
x = np.linspace(0, 4*np.pi, num=num_points)
```

The above creates a NumPy array with `num_points` equally spaced values between $0$ and 
$4 \pi$, including the end points. We can check this for a smaller example: 

```{python}
print(np.linspace(0, 2, num=10))
```

To evaluate $\sin(x)$ for each value in the array `x`, we use the NumPy `sin` function, which can be applied entry-wise to `x`:

```{python}
f = np.sin(x)
```

We can now plot `f` against `x`.

```{python}
plt.plot(x, f)
plt.xlabel('$x$')
plt.ylabel('$\sin(x)$');
```

We can improve the appearance of the plot by specifying the $x$ limits:

```{python}
# Plot the graph
plt.plot(x, f)

# Label the axis
plt.xlabel('$x$')
plt.ylabel('$\sin(x)$')

# Use the start and end values in x as x limits (recall that x[-1] 
# returns the last value in x)
plt.xlim(x[0], x[-1]);
```

To plot two functions on one graph, we use `plt.plot` twice:

```{python}
x = np.linspace(0, 4*np.pi, num=100)

# Plot sin(x) and cos(x), and add label for each
plt.plot(x, np.sin(x), label="$\sin(x)$")
plt.plot(x, np.cos(x), label="$\cos(x)$")

# Label the x-axis
plt.xlabel('$x$')

# Add legend
plt.legend()

# Use the start and end values in x as x limits
plt.xlim(x[0], x[-1]);
```

# Bar charts and histograms


## Bar charts

The numbers of students in each year of the Engineering Tripos, and graduate students are:

```{python}
cohort = ('IA', 'IB', 'IIA', 'IIB', 'Graduate')
num_students = (332, 270, 256, 238, 451)
```

We want to represent these figures using a bar chart:

```{python}
# Create an array with the position of each bar along the x-axis, e.g [0, 1, 2, 3, 4] 
x_pos = np.arange(len(cohort))

# Produce bar plot
plt.bar(x_pos, num_students, align='center');

# Replace the x ticks with the Tripos name, and rotate labels 30 degrees
plt.xticks(x_pos, cohort, rotation=30)

# Add axis labels 
plt.xlabel('cohort')
plt.ylabel('number of students');
```

## Histograms

To create a histogram we first need a data set. We will use 4000 random values drawn from a normal (Gaussian) distribution with zero mean and standard deviation of one. We can use NumPy to create such an array using:

```{python}
# loc=mean, scale=stddev, size=num samples
x = np.random.normal(loc=0.0, scale=1.0, size=100)  
```

We can visualise the distribution of the values using a histogram.
A histogram works by collecting data into intervals (bins) along the horizontal axis. 
The number of values that fall within a 'bin' is then displayed on the vertical axis.
Using 20 bins, we can visualise how `x` is distributed:

```{python}
# Produce histogram with 20 bins (try changing the number of bins)
n, bins, patches = plt.hist(x, 20, facecolor='green');

# Add label
plt.xlabel('value')
plt.ylabel('frequency');
```

Matplotlib has automatically created 20 bins of equal width, and computed the number of entries in each bin. We can inspect the bin intervals

```{python}
print(bins)
```

And the number of values in each bin:

```{python}
print(n)
```

```{python}

```

We can mix plot types on a single graph - in the case of a histogram it can be useful to compare against
a probability density function. Since we drew the values in `x` from a normal distribution, we expect a normal probability distribution function to be a good fit. Let's test.

We can use the module `scipy.stats` to compute the normal probability distribution function. To compare the histogram to a probability density function, the histogram needs to be 'normalised' 
(so the integral is equal to 1).

```{python}
# Import norm from SciPy stats module to compute norm probability distribution function

from scipy.stats import norm

# Plot normed histogram of data
n, bins, patches = plt.hist(x, 10, density=1.0, facecolor='green', alpha=.75);

# Create array of 100 equally spaces points, stating from the first value in the bins
# through to the last values in the bins
xf = np.linspace(bins[0], bins[-1], 1000)

# Evaluate normal probability density function (pdf) at each xf
f = norm.pdf(xf)

# Create line plot of normal probability distribution function (blue line)
plt.plot(xf, f, 'b')

# Add labels
plt.xlabel('value')
plt.ylabel('frequency');
```

Experiment with the histogram plots by changing the number of samples and the number of bins.


# Pie charts

At the time of the 2011 census, the population of Cambridgeshire by district was:

District              | Population
---------------------:|------------:
Cambridge City        | 123900
East Cambridgeshire   | 83800
Fenland               | 95300
Huntingdonshire       | 169500
South Cambridgeshire  | 148800

As part of a presentation to the Cambridge City council, we need to produce
a pie chart of the Cambridgeshire population by district, indicating the percentage of
residents in each district and highlighting the Cambridge City 'slice'.

To do this, we first enter the data into tuples :

```{python}
district = ('Cambridge City', 'East Cambridgeshire', 'Fenland', 'Huntingdonshire',
            'South Cambridgeshire')
population = (123900, 83800, 95300, 169500, 148800)
```

Tuples are appropriate because the number of districts is fixed (recall that we can't change the length of a tuple).

We next produce a colour pie chart:

```{python}
# Specify slice colours 
# (see http://stackoverflow.com/questions/22408237/named-colors-in-matplotlib)
colors = ['yellowgreen', 'gold', 'lightskyblue', 'lightcoral', 'red']

# "explode" the 1st slice (Cambridge City)
explode = (0.1, 0, 0, 0, 0)  

# Produce pie chart. The slices will be ordered and plotted counter-clockwise.
plt.pie(population, explode=explode, labels=district, colors=colors,
        autopct='%1.1f%%', shadow=True, startangle=90)

# Add title
plt.title("2011 population distribution in Cambridgeshire");
```

# Interactive plots

Interactive plots are great ways to explore the influence of parameters on a response.
As a simple example, we want to plot

$$
f(t) = t^{\alpha} \sin(\omega t)
$$

where $\alpha$ and $\omega$ are parameters. We would like to explore interactively the
influence of the two parameters.


## Installing widget extensions

Interactive plots be can created using the interactive widgets module `ipywidgets`. 
Interactive widgets have been configured for you  on https://notebooks.azure.com/.
To install the widgets on your own computer, follow the instructions at https://ipywidgets.readthedocs.io/en/latest/user_install.html.


We first import a function from the `ipywidgets` module:

```{python}
from ipywidgets import interact
```

## Creating interactive plots

To create an interactive plot, we need to encapsulate our plot code inside a function, with the plot parameters as argument to the function:

```{python}
def plot(a=1, w=0):
    t = np.linspace(0, 2*np.pi, 200)
    plt.xlabel('$t$')
    plt.ylabel('$f$')
    plt.title(r"$\alpha$ = {}, $\omega$ = {}".format(a, w))
    plt.plot(t, (t**a)*np.sin(w*t))
```

(Remember, to get $\omega$ and $\alpha$ use `\omega` + `Tab` key and `\alpha` + `Tab` key.)
We have used default function arguments - these will be the initial parameters for out interactive plot.

Next, we use the `interact` function, passing to it the name of our function that does the plotting 
(`plot` in this case), and a tuple for each parameters:

```{python}
interact(plot, a=(-10, 10, 0.25), w=(0, 2, 0.25));
```

If you have interactive widgets working, you should see two sliders above the plot that you can adjust.
The plot should dynamically change.

The tuple for each parameters has the form `(end_point0, end_point1, step_size)` for the slider.


## Advanced interactive plot creation (optional)

There is a compact way of constructing interactive plots using function *decorators*. Decorators are not required for this course, so this section is optional. If you are interested, you can find lots of information on decorators online.

Below is the interactive plot example constructed using a decorator. 

```{python}
@interact(a=(-10, 10, 0.25), w=(0, 2, 0.25))
def plot(a=1, w=0):
    t = np.linspace(0, 2*np.pi, 200)
    plt.xlabel('$t$')
    plt.ylabel('$f$')
    plt.title(r"$\alpha$ = {}, $\omega$ = {}".format(a, w))
    plt.plot(t, (t**a)*np.sin(w*t))
```

The decorator
```python
@interact(ω =(-10, 10, 0.25), α=(0, 2, 0.25))
```
is a 'shortcut' that creates the line
```python            
interact(plot, ω=(-10, 10, 0.25), α=(0, 2, 0.25))
```    
for us.


# Contour plots

Consider the function of two variables:

$$
f(x, y) = \sin(x) \cos\left(\frac{xy^2}{10}\right)
$$

It is not easy to visualise the form of this function. One way to visualise the function is to create a contour plot. To do this, we first create points in the $x$ and $y$ directions at which we want to evaluate the function: 

```{python}
N = 50  # 50 points in each direction
x = np.linspace(-np.pi, np.pi, N)
y = np.linspace(-np.pi, np.pi, N)
```

Next, we use NumPy to create a 'grid' of $(x, y$) points: 

```{python}
X, Y = np.meshgrid(x, y)
```

If you want to explore what `meshgrid` returns, try making `N` smaller and printing `X` and `Y` to the screen.

We now evaluate the function $f$ at each point:

```{python}
f = np.sin(X)*np.cos((X*Y**2)/10)
```

and then create a filled contour plot using `plt.contourf`:

```{python}
plt.contourf(X, Y, f,  cmap=matplotlib.cm.PuBu_r)
plt.colorbar();  # Add colour bar (legend)
```

Above, we have chosen a built-in Matplotlib colour map (`matplotlib.cm.PuBu_r`). Without passing the `cmap` argument we would have seen the default colour map, which is `matplotlib.cm.jet` (and which is ugly).

To create a contour map using contour lines:

```{python}
# Plot
p = plt.contour(X, Y, f)

# Add contour labels
plt.clabel(p, inline=1);
```

There is more we could do, for example controlling the numbers of contour lines.


# Three-dimensional plot (optional)

*This is advanced example. Skip over this if you wish.*

Another way to represent a function of two variables is to use a three-dimension plot, with axes for $x$, 
$y$, and $f$. Plotting in three dimensions is considerably more complex that in two dimensions.

To create a three-dimensional plot, we need to import some extra modules from Matplotlib:

```{python}
from mpl_toolkits.mplot3d import axes3d
from matplotlib import cm
```

The below plots the function $f(x, y)$ in three-dimensions:

```{python}
fig = plt.figure()
ax = fig.gca(projection='3d')

surf = ax.plot_surface(X, Y, f, rstride=1, cstride=1, cmap=cm.coolwarm,
                       linewidth=0, antialiased=False)
                                              
ax.set_xlabel('$x$')
ax.set_ylabel('$y$')

ax.view_init(elev=45);
```

# Plotting data from online resources - stock data

It becoming increasingly common to fetch data from the Internet for processing and plotting, and more and more data is being made available, especially government data.

To start, we will plot the Rolls Royce stock price over recent years. To fetch financial data, the library
`quandl` (https://www.quandl.com/tools/python) is helpful. It was installed at the top this
notebook. We first import the module:

```{python}
import quandl
```

*You may need to register for a [free API key with Quandl](https://docs.quandl.com/docs#section-authentication) if you run the code blocks several times.*

*If you run into package import errors, it means you have multiple Python installations. You should use the [virtual environment feature in Anaconda](https://conda.io/docs/user-guide/tasks/manage-environments.html).*


We then fetch the Rolls Royce stock prices on the London Stock Exchange:

```{python}
adyen_stock_data = quandl.get("EURONEXT/ADYEN", returns="numpy")  # "LSE/RR" is the code on quandl for the Rolls Royce stock price 
```

We now have `rr_stock_data` as a special type of NumPy array called a `recarray` (http://docs.scipy.org/doc/numpy/reference/generated/numpy.recarray.html):

```{python}
print(type(adyen_stock_data))
```

A `recarray` is is a two-dimensional array for which we can extract columns by an associated name. We can check the names using `recarray.dtype`:

```{python}
print(adyen_stock_data.dtype)
```

Extracting the `Date` and `Price` columns, we can plot the Rolls Royce stock price over time:

```{python}
# Plot the stock price
plt.plot(adyen_stock_data['Date'], adyen_stock_data['Last'])

# Add axis labels and plot title
plt.ylabel("stock price (p)")
plt.xlabel("year")
plt.title("Adyen Holdings stock price")

# Rotate the year tick labels
plt.xticks(rotation=70);
```

Similarly, we can plot the trading volume (in thousands):

```{python}
plt.plot(adyen_stock_data['Date'], adyen_stock_data['Volume']/1000.0)
plt.ylabel("trades ('000)")
plt.xlabel("year")
plt.title("Rolls Royce trading volume")
plt.xticks(rotation=70);
```

# Exercises


## Exercise 08.1 (function plotting)

Consider the function 

$$
f(x) = e^{x/10} \sin(\omega_{1}x)\cos(\omega_{0}x)
$$

from $x = -4\pi$ to $x = 4\pi$.  

1. Plot the function when $\omega_{0} = \omega_{1} = 1$. Label the axes.
1. Create an interactive plot with sliders for $\omega_{0}$ and $\omega_{1}$, varying from 0 to 2.

```{python}
@interact(w0 =(0, 2, 0.1), w1 =(0, 2, 0.1))
def plot(w0 = 1, w1 =1):
    N = 100
    x = np.linspace(-4*np.pi, 4*np.pi, N)
    plt.xlabel('x')
    plt.ylabel("y")
    plt.title(r"$\omega0$ = {}, $\omega1$ = {}".format(w0, w1))
    plt.plot(x, ((np.e**(x/10))*(np.sin(w0*x))*(np.cos(w1*x))))
    


```

## Exercise 08.2 (multiple function plotting)

1. Plot the function 

   $$
   f(x)  = \frac{\sin(x)}{x}
   $$

   from $x = -6\pi$ to $x = 6\pi$. Think carefully about which $x$ values you use when 
   $x$ is close to zero.
  
1. Add to the above plot the graph of $1/ \left| x \right|$, and limit the range of the $y$ axis to 1 using
   `plt.ylim`. (Hint: use `np.abs(x)` to return the absolute values of each 
   component of a NumPy array `x`. 

```{python}
x = np.linspace(-6*np.pi, 6*np.pi, 100)

f = (np.sin(x)) / x

plt.xlabel("x")
plt.ylabel("f(x)")
plt.plot(x, f)

f1 = 1 / np.abs(x)

plt.ylim(top = 1)
plt.plot(x, f1)


```

## Exercise 08.3 (demographics and interactive plotting)

A county planning body has requested an interactive tool to visualise the population distribution in Cambridgeshire (by district) from 2011 to 2021 for different population growth rate scenarios in each district. It can be assumed that:

- the growth rates are constant in each district;
- the growth rate will not be negative in any district; and 
- the annual growth rate in any one district will not exceed 10%.

Building on the pie chart example with population data in the body of the notebook, create an interactive plot with:

1. A slider for the year (from 2011 to 2021); and
2. Sliders for the annual population growth for each district (in percentage), with an 
   initial value of zero for each district.

```{python}
@interact(year = (2011, 2021, 1), g0 = (0, .10, 0.01), g1 = (0, .10, 0.01), g2 = (0, .10, 0.01), g3 = (0, .10, 0.01), g4 = (0, .10, 0.01))
def population_growth(year = 2011, g0 = 0, g1 = 0, g2 = 0, g3 = 0, g4 = 0):

    district = ('Cambridge City', 'East Cambridgeshire', 'Fenland', 'Huntingdonshire',
                'South Cambridgeshire')
    population_2011 = (123900, 83800, 95300, 169500, 148800)
    population_growth = (population_2011[0] * (1 + g0)**(year - 2011), population_2011[1] * (1 + g1)**(year - 2011),
                         population_2011[2] * (1 + g2)**(year - 2011), population_2011[3] * (1 + g3)**(year - 2011),
                         population_2011[4] * (1 + g4)**(year - 2011))
    
    
    # Specify slice colours 
    # (see http://stackoverflow.com/questions/22408237/named-colors-in-matplotlib)
    colors = ['yellowgreen', 'gold', 'lightskyblue', 'lightcoral', 'red']

    # "explode" the 1st slice (Cambridge City)
    explode = (0.1, 0, 0, 0, 0)  
    

    # Produce pie chart. The slices will be ordered and plotted counter-clockwise.
    plt.pie(population_growth, explode=explode, labels=district, colors=colors,
            autopct='%1.1f%%', shadow=True, startangle=90)
    
    #label sliders
    plt.title(r"Cambridge City = {}, East Cambridgeshire = {}, Fenland = {}, Huntingdonshire = {}, South Cambridgeshire = {}".format(g0, g1, g2, g3, g4))



    
    




```

<!-- #region -->
## Exercise 08.4 (crime reports by location)


### Background

Your task is to produce a crime report data plot in the neighborhood of your college, by reported crime
category. It will be interesting to see how this varies between colleges!

We can get crime data in the UK from the police data systems using what is known as a REST API,
and turn the data into a list of Python dictionaries. Each entry in the list is a police report 
(an entry is a Python dictionary detailing the report).

The first step is the import the modules we will be using:
<!-- #endregion -->

```{python}
import json
import requests
```

The service https://data.police.uk has an interface where we can add specific strings to the URL (web address) to define what data we are intersted in, and the police server will return our requested data. The format is

    https://data.police.uk/api/crimes-street/all-crime?poly=[LAT0],[LON0]:[LAT1],[LON1]:[LAT2,LON2]&date=YYYY-MM
    
This return crimes reports in the triangle given by the three geographic coordinate points `(latitude0, longitude0), (latitude1, longitude1) and (latitude2, longitude2)`, for the month `YYY-MM`.          

Below we create this URL string to include a large part of the Cambridge city centre. You can modify this for your own college or other area of interest (Google Maps is a handy way to get the geographic coordinates).

```{python}
# A triangle that includes most of the Cambridge city centre
# (long, lat) for three vertices of a triangle (no spaces!)

#51.516153,-0.1199042
#51.5170482,-0.1159934
#51.5131457,-0.1172553

p0 = '51.516153,-0.1199042'
p1 = '51.5170482,-0.1159934'
p2 = '51.5131457,-0.1172553'

# year-month of interest
year_month = '2019-9'
year_month_p = '2018-9'

# Construct request URL string using the above data
url = 'https://data.police.uk/api/crimes-street/all-crime?poly=' + p0 + ':' + p1 + ':' + p2 + '&date=' + year_month
url_p = 'https://data.police.uk/api/crimes-street/all-crime?poly=' + p0 + ':' + p1 + ':' + p2 + '&date=' + year_month_p

# Fetch data from https://data.police.uk
r = requests.get(url)
r_p = requests.get(url_p)

```

The following converts the fetched data into a list of dictionaries:

```{python}
crime_data = r.json()
crime_data_p = r_p.json()
```

To get an idea of how the data is arranged, we can look at the first report in the list. To make the displayed data easier to read, we use the 'pretty print' module `pprint`.

```{python}
import pprint
if crime_data:
    pprint.pprint(crime_data[0])
```

<!-- #region -->
### Task


Produce a bar chart of the number of reports in different categories. The categories are: 
<!-- #endregion -->

```{python}
categories = ('anti-social-behaviour', 'bicycle-theft', 'burglary', 'criminal-damage-arson', \
              'drugs', 'other-crime', 'other-theft', 'public-order', 'shoplifting', \
              'theft-from-the-person', 'vehicle-crime', 'violent-crime')

```

Run your program for different parts of Cambridge, starting with the area around your college, and for different months and years.


#### Hints:

Create an empty dictionary, which will eventually map the report category to the number of incidents:

```{python}

```

Iterate over all reports in the list, and extract the category string from each report. If the category string (the 'key') is already in the dictionary increment the associated counter. Otherwise add the key to the dictionary, and associate the value 1.

```{python}
# Iterate over all reports
# trying to superimpose two bar charts on one axis. 
# Take another look at the values for the x-axis, not sure what's going wrong.

import numpy as np

fig, ax = plt.subplots()
width = 0.35

categories_freq = {}

for report in crime_data:
    # Get category type from the report
    category = report['category']
    
    if category in categories_freq:
        categories_freq[category] += 1
        
    else:
        categories_freq.update({category : 1})
        
x = list(np.arange(len(categories_freq)))

categories_freq_p = {}

for report in crime_data_p:    
    
    category = report['category']
    
    if category in categories_freq_p:
        categories_freq_p[category] += 1
        
    else:
        categories_freq_p.update({category : 1})

x_p = list(np.arange(len(categories_freq_p)))

x_c = x + [i for i in x_p if i not in x]
x_c = np.arange(len(x_c))

bar_0 = ax.bar(x_c, categories_freq.values(), width)
bar_1 = ax.bar(x_c + width, categories_freq_p.values(), width)

ax.set_xticks(x_c)
ax.set_title("Frequencey of crimes near LSE, June 2019/2018")

plt.show()
```

When adding the tick labels (crime categories), it may be necessary to rotate the labels, e.g.:
```python
plt.xticks(x_pos, categories, rotation='vertical')
```


### Extensions (optional)

1. Probe the retrieved data to build a set of all crime categories in the data set.
2. Explore the temporal (time) aspect of the data. Thinks of ways to represent the change in reported incident 
   types over time.

```{python}
crime_categories_comp = []
```

```{python}
for report in crime_data:
    category = report['category']
    
    if category in crime_categories_comp:
        pass
    else:
        crime_categories_comp.append(category)

print(crime_categories_comp)
print(len(crime_categories_comp))
```

```{python}

```
